### ISSUE TITLE
Re-define the relayer categories

### ISSUE THREAD

**Issue by lukerQuant** [EntEthAlliance/dlt-interop#1]
## About you

**Name:** [Luke Riley](https://www.linkedin.com/in/luke-riley-36484221/)
**Organization/Company:** [Quant](https://quant.network/)

## About your review

**Document:** EEA DLT Interoperability Specification</br>

Note: this is a really good piece of work, congratulations to the authors and to the EEA working group.

**Section:** https://entethalliance.github.io/crosschain-interoperability/draft_dlt-interop_techspec.html#crosschain-message-relays </br>

**Comments/Suggestions/Feedback**

I disagree with Oracle being a particular relay sub-type. According to the ISO/TC 307 definitions (found [here](https://www.iso.org/obp/ui/en/#iso:std:iso:22739:ed-2:v1:en)), all the relays types listed are oracles. Copying the oracle definitions from the linked document:

- DLT oracle (distributed ledger technology oracle): service that updates a distributed ledger using data from outside of a DLT system

Hence why the Oracle category was used as one of the two main interoperability solution types in section 3.3.3 [here](https://dl.acm.org/doi/full/10.1145/3564532).

So my general proposal for this section is to rename the Oracle Relay to something else, and introduce a higher level introduction, potentially about the different interoperability modes and interoperability solutions discussed in [here](https://dl.acm.org/doi/full/10.1145/3564532) (as ISO/TC 307's Interoperability Framework is set to use a similar structure as this paper).

**Comment by anaisofranc** [comment]
We have discussed this issue. We agreed to update as per below: 

1. 'Oracle Relay' to be changed to 'Type 1 Relay' and to add context including ISO definition.
2.  Add "Interoperation Modes"  as per section 3.3.1 Interoperation Modes in [this paper](https://dl.acm.org/doi/full/10.1145/3564532) and align with ISO Interoperability Framework as a sub-section in section ['7. Considerations' ](https://entethalliance.github.io/crosschain-interoperability/draft_dlt-interop_techspec.html#sec-gen-considerations).

**Comment by lukerQuant** [comment]
Dear @anaisofranc,

That sounds like a good plan.

Thank you for your feedback on this, and thank you to the EEA cross-chain interoperability working group for their help regarding aligning standards across different Standards Developing Organisations.

Best wishes

**Comment by anaisofranc** [comment]
Draft specification updated to address this issue.

**Comment by anaisofranc** [comment]
We will update the flow for this paragraph to be consistent with the way we describe the other items: "Oracle Relay (Type 1): ISO 22739:2024 defines a DLT oracle as a "service that updates a distributed ledger using data from outside of a DLT system". The ISO Blockchain and Distributed Ledger Technology — Interoperability Framework (ISO/CD TS 23516) categorize oracle interoperability solutions as "Type 1". One possible implementation consists of dedicated Oracle smart contracts deployed on the target chain to handle incoming messages. Oracle nodes run independent off-chain server infrastructure that retrieves data and events from the source system through custom integrations. They collate this external information into standard formats understandable by the oracle contract on the target side. The oracle nodes transmit batched communications to the oracle contracts, which in turn expose APIs for other on-chain smart contracts to access the bridged data. This facilitates target side consumption of verified external data. The model operates through a trust-based federation of oracle nodes which follow expected security practices. By moving the message relaying to dedicated infrastructure operators who stitch source and target chains via custom software, a high degree of flexibility and efficiency is achieved. However lack of decentralization and use of trusted nodes implies some security assumptions for oracle relay versus other peer-to-peer messaging approaches between chains."

**Comment by anaisofranc** [comment]
This issue has now been addressed.
