### ISSUE TITLE
Consider a processing stage between origin and destination network

### ISSUE THREAD

**Issue by lukerQuant** [EntEthAlliance/dlt-interop#2]
## About you

**Name:** [Luke Riley](https://www.linkedin.com/in/luke-riley-36484221/)
**Organization/Company:** [Quant](https://quant.network/)

## About your review

**Document:** EEA DLT Interoperability Specification</br>
**Section:** https://entethalliance.github.io/crosschain-interoperability/draft_dlt-interop_techspec.html#crosschain-message-definition </br>

**Comments/Suggestions/Feedback**

*This is an editorial suggestion - with the potential to have a feature change impact*.

When reading through this section, I believe that this specification does not allow for a processing stage between data being picked up from the origin blockchain, and placed on the destination blockchain. I could see this being a requirement for some use cases. E.g. prices are read from multiple DEXs and then averaged out before being placed on the destination blockchain.

At the moment I am looking for a comment around the appropriateness of your specification for this type of use case.

**Comment by anaisofranc** [comment]
Yes, the specification accommodates this use case. Data interpretation and processing should be done at the application layer.  We will add this consideration to section 5. Crosschain Application Layer.

**Comment by anaisofranc** [comment]
Draft specification updated to address this issue.
