### ISSUE TITLE
Smooth the transition from high level to specific?

### ISSUE THREAD

**Issue by lukerQuant** [EntEthAlliance/dlt-interop#3]
## About you

**Name:** [Luke Riley](https://www.linkedin.com/in/luke-riley-36484221/)
**Organization/Company:** [Quant](https://quant.network/)

## About your review

**Document:** EEA DLT Interoperability Specification</br>
**Section:** https://entethalliance.github.io/crosschain-interoperability/draft_dlt-interop_techspec.html#crosschain-verifier-interface </br>

**Comments/Suggestions/Feedback**

To me, the specification seemed to go quite quickly from high level/background level information to specific required interfaces. I felt like there could be a benefit for smoothing the flow, potentially by placing 3.1 and 3.2 into section 2 and renaming that section.

**Comment by anaisofranc** [comment]
3.1 and 3.2 are related to the Message Layer, so it is best to leave them under section 3 rather than in section 2. Architecture of the Crosschain Protocol Stack. However, we understand that the transition could be smoother, so we will add a paragraph after sub-section 3.2.

**Comment by anaisofranc** [comment]
Draft specification updated to address this issue.

**Comment by anaisofranc** [comment]
Anaïs to check why the update is not reflected in the document.

**Comment by anaisofranc** [comment]
This issue has now been addressed by adding a paragraph to transition from section 3.2 to section 3.3
