### ISSUE TITLE
[Editorial]

### ISSUE THREAD

**Issue by findthomas** [EntEthAlliance/dlt-interop#4]
## About you

Please include your name so your contribution can be publicly acknowledged in the final publication.

**Name:** </br>
**Organization/Company:**</br>

## About your review

**Document:** EEA DLT Interoperability Specification</br>
**Section:** Use the URL to identify the right section of the document. </br>

**Comments/Suggestions/Feedback**

Please write your comment, suggestion or feedback here.

The current EEA Interoperability Technical Specification Draft seem to be three (3) specifications rolled-up into 1 document.  The three parts could be separate documents (Messaging (Sect 3); Function Calls (Sect 4); Application coordination (Sect 5)).

Having a top level Architecture document and 3 separate drafts has several advantages from an editorial perspective. Each of the three specifications could be updated independently without necessarily updating the others.

Just a suggestion.

**Comment by anaisofranc** [comment]
We used to have three separate documents; however, we received feedback from some stakeholders that it is beneficial to have one consolidated specification due to dependencies.
