### ISSUE TITLE
Introduction part to Section 3.

### ISSUE THREAD

**Issue by findthomas** [EntEthAlliance/dlt-interop#5]
## About you

Please include your name so your contribution can be publicly acknowledged in the final publication.

**Name:** </br>
**Organization/Company:**</br>

## About your review

**Document:** EEA DLT Interoperability Specification</br>
**Section:** Use the URL to identify the right section of the document. </br>

**Comments/Suggestions/Feedback**

Please write your comment, suggestion or feedback here.

It would be useful to clarify early in Section 3 that the term "messaging" is used to mean communicating information data between EVM nodes.  The word "messaging" is very common term and loaded.

Perhaps something like the following lines could open Section 3:

[begin]

The Crosschain Messaging layer establishes the peer-to-peer communications infrastructure that enables interoperation between blockchain or DLT networks.

The nodes in the network take an active role in maintaining the authentication, integrity protection and confidently of information transmitted between the blockchains.

Several cryptographic approaches to afford these protections are available. The application developer needs to take these options into consideration when developing decentralized applications which utilize the cross-chain messaging functions.

[end]

**Comment by anaisofranc** [comment]
We will add update the first sentence of the paragraph to "The Crosschain Messaging layer establishes the peer-to-peer communications infrastructure that enables interoperation between blockchain or DLT networks." as suggested.

We believe that the second sentence is assumed for any DLT. We only cover DLT to DLT interaction.  "The nodes in the network take an active role in maintaining the authentication, integrity protection and confidently of information transmitted between the blockchains.".

We will add the third sentence "Several cryptographic approaches to afford these protections are available. The application developer needs to take these options into consideration when developing decentralized applications which utilize the cross-chain messaging functions." to the introduction of section 3.

**Comment by anaisofranc** [comment]
Draft specification updated to address this issue.
